[project]
name = "yummylogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylognet",
]

[tool.uv.sources]
pylognet = { git = "https://github.com/upiscium/pylognet" }
